### ISSUE TITLE
Not show all list and clickable link

### ISSUE THREAD

**Issue by careerhub-source** [vedmant/laravel-feed-reader#11]
I put the following in latest.blade.php but not show all post and no click link to redirect to original website.
how can solve this.
`<?php			
$f = FeedReader::read('http://rss.careerjet.com/rss?l=USA&lid=55&affid=b5145f67f36b6e90de03223fe8279065&psz=50&snl=400');

echo $f->get_title();
echo $f->get_items()[0]->get_title();

echo $f->get_items()[0]->get_content();

?>`
Find attached image for the result in frontend
![rss](https://user-images.githubusercontent.com/46191803/111074288-6321a200-84f3-11eb-91a1-cb0bd9d64694.JPG)

**Comment by vedmant** [comment]
@kiwango Try `echo $f->get_items()[0]->get_link();` check your XML document.

**Comment by careerhub-source** [comment]
@vedmant  Thanks for quick reply, unfortunately does work issue #11 , what I want is to fetch data from other site to my site. But the result show only one post  and not a clickable, where the user can not click and be redirected to that site.
