### ISSUE TITLE
@vedmant  Thanks for quick reply, unfortunately does work issue #11 , 

### ISSUE THREAD

**Issue by careerhub-source** [vedmant/laravel-feed-reader#12]
@vedmant  Thanks for quick reply, unfortunately does work issue #11 , what I want is to fetch data from other site to my site. But the result show only one post  and not a clickable, where the user can not click and be redirected to that site.

_Originally posted by @kiwango in https://github.com/vedmant/laravel-feed-reader/issues/11#issuecomment-798935624_

**Comment by vedmant** [comment]
@kiwango Sorry, it's unlikely that there is any problem with the packages, re-check your code, see http://simplepie.org/wiki/reference/simplepie/start for more info
