### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by olvakulin** [vedmant/laravel-feed-reader#13]
Hey! I have images in the channel and I need to display them on my site. How can I best get them.
`<description><img width="500" height="314" src="https://www.travelnewshub.com/wp-content/uploads/2021/04/world-economic-forum-positive-tech-solutions-will-forge-the-recovery.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" loading="lazy" /></div>Tokyo</description>` only img.  I would really appreciate any help!!!

**Comment by vedmant** [comment]
@olvakulin You can use regex expression like this `/<img .*?>/gm` check php docs about regex
