### ISSUE TITLE
Not able to get image from <itunes:image href=""> tag

### ISSUE THREAD

**Issue by vinayakarasid** [vedmant/laravel-feed-reader#15]

**Comment by vedmant** [comment]
@vinayakarasid What RSS URL do you use?

**Comment by vinayakarasid** [comment]
I got the solution like below
$item->get_item_tags(SIMPLEPIE_NAMESPACE_ITUNES,'image')[0]['attribs']['']['href']
But it can be in much simpler way like directly calling fuction for it.
