### ISSUE TITLE
Config publish does not work

### ISSUE THREAD

**Issue by whollaus** [vedmant/laravel-feed-reader#2]
$ php artisan vendor:publish --provider="Awjudd\FeedReader\FeedReaderServiceProvider"
Unable to locate publishable resources.

$ php artisan vendor:publish
Can't locate path: </srv/http/***/vendor/vedmant/laravel-feed-reader/src/../../config/feed-reader.php>

**Comment by vedmant** [comment]
@whollaus Thanks for the issue. Fixed it in the latest release. The command to publish config:

```
php artisan vendor:publish --provider="Vedmant\FeedReader\FeedReaderServiceProvider"
```
