### ISSUE TITLE
repository 'https://github.com/hautelook/phpass.git/' not found

### ISSUE THREAD

**Issue by ctc-web-dev-allied** [vedmant/laravel-feed-reader#24]
when trying to install via command "composer require vedmant/laravel-feed-reader"
getting error repository 'https://github.com/hautelook/phpass.git/' not found

How to fix this?

**Comment by vedmant** [comment]
@ctc-web-dev-allied Probably you have some wrong configuration in your composer.json, there is no references to `https://github.com/hautelook/phpass.git/` in this repo or dependencies

**Comment by ctc-web-dev-allied** [comment]
Got it. Thanks
