### ISSUE TITLE
Curl error "60 SSL unable to get local issuer"

### ISSUE THREAD

**Issue by umigliore** [vedmant/laravel-feed-reader#7]
FEATURE REQUEST
Hello, for some sites the Curl gives errors for broken or selfsigned certs.
In simplepie there is possibility to use curl_options to avoid ssl verify, can you add this option to your framework?

Thanks!

cfr [https://github.com/simplepie/simplepie/pull/407](https://github.com/simplepie/simplepie/pull/407)
```
$simplePie = new SimplePie();
            $simplePie->set_curl_options(
                array(
                    CURLOPT_SSL_VERIFYHOST => false,
                    CURLOPT_SSL_VERIFYPEER => false
                )
            );
```

**Comment by vedmant** [comment]
@umigliore Thanks, published new release. I didn't test it, let me know if it's not working. I updated configuration file with new option.

**Comment by umigliore** [comment]
It works fine, thanks !
